Bug fixes
evgeny-sav/notes-app pull request #40
Opened 2016-10-18 13:50 UTC by evgeny-sav

* Redirect to Notes List after Login
* Redirect to Welcome after Logout
* List/Grid view modes added
* ManageUsers grid's pagination modified

2016-10-18 14:22 UTC, alekseyC64 commented on notes_app/client/app/users/users_list.component.js
> +//      paginationPageSizes: [5,10,25],
please don't leave commented out code. Usually it's not needed, but if you need this - leave an explanation around

2016-10-18 14:22 UTC, alekseyC64 commented on notes_app/client/app/users/users_list.component.js
> +
too many empty lines, 1 is enough

2016-10-18 14:31 UTC, alekseyC64 commented
@evgeny-sav it's is really hard to review such combined PRs. It's a common practice to do PR per bug or something.

2016-10-19 09:50 UTC, dglebovskiy commented on notes_app/client/app/login/login.component.js
> +        $state.go('main.note.list');
A suggestion: we could move this to MainController, using the result promise returned by $uibModal.open.

2016-10-19 15:05 UTC, alekseyC64 commented on notes_app/client/notes.js
> +      'url': '-listview',
it's kind of confusing, let's keep use standard urls, where delimiter is `/`

2016-10-19 15:06 UTC, ghost commented on notes_app/client/notes.js
> +          return userService.session();
basically it will call backend for session every state change. It doesn't look like the best solution. Basically, it could be managed on ui-states controllers or `resolve` sections, or `onEnter` sections if session was already resolved.

2016-10-21 13:13 UTC, alekseyC64 commented on notes_app/client/app/users/user_service.js
> +      'checkSession': function() {
it looks pretty close to `session`, does it make sense to create a separate?

2016-10-21 13:14 UTC, alekseyC64 commented on notes_app/client/notes.js
> +        userService.checkSession().then(function(session){
you're still trying to load session on every state change. It doesn't look good. You have to do it only when page is refreshed or app is opening in browser

2016-10-24 09:39 UTC, evgeny-sav commented on notes_app/client/notes.js
> +        userService.checkSession().then(function(session){
`you're still trying to load session on every state change` - yes. 
Because when I am refreshing the page it reloads the whole app again and sets `userService.user.logged_in: false` by default, so it redirects on `/welcome` state. I tried to store `user's object` into `localStorage` so after refreshing the page it could check the whether is user logged in or not and decide where to redirect but you said I shouldn't use `localStorage`.

So what should I do if I can't use `session` and `localStorage`?

2016-10-24 09:45 UTC, evgeny-sav commented on notes_app/client/notes.js
> +        userService.checkSession().then(function(session){
please, give me a little tip how to implement this.

2016-10-24 09:48 UTC, ghost commented on notes_app/client/notes.js
> +        userService.checkSession().then(function(session){
@evgeny-sav you can check my [first comment ](https://github.com/evgeny-sav/notes-app/pull/40#discussion_r84092193)

> Basically, it could be managed on ui-states controllers or resolve sections, or onEnter sections if session was already resolved.

2016-10-24 09:56 UTC, ghost commented on notes_app/client/notes.js
> +        userService.checkSession().then(function(session){
Did you check https://github.com/angular-ui/ui-router/wiki/Nested-States-%26-Nested-Views#inherited-resolved-dependencies ? you can get user on parent state, and then you can check it in any child (in `resolve` or in `onEnter` state section)

2016-10-24 13:50 UTC, alekseyC64 commented on notes_app/client/notes.js
> +        if (!user.data.is_superuser || !user.logged_in) {
I think it's enough to check `is_superuser` only here.

2016-10-24 13:51 UTC, alekseyC64 commented on notes_app/client/notes.js
>      $rootScope.$on('$stateChangeStart',
I think you can delete this handler, it looks empty to me

2016-10-24 13:52 UTC, ghost requested changes
lef some comments

2016-10-24 13:56 UTC, dglebovskiy commented on notes_app/client/notes.js
> +      function(event, toState, toParams, fromState, fromParams, options) {});
Is that an empty callback? It probably could be removed along with the whole run block.

2016-10-24 14:56 UTC, evgeny-sav commented on notes_app/client/notes.js
> +        if (!user.data.is_superuser || !user.logged_in) {
i have checked it for `is_superuser` at first but it turned out that it's not enough.

2016-10-24 14:57 UTC, evgeny-sav commented on notes_app/client/notes.js
>      $rootScope.$on('$stateChangeStart',
I am agree

2016-10-24 14:58 UTC, evgeny-sav commented on notes_app/client/notes.js
> +      function(event, toState, toParams, fromState, fromParams, options) {});
I am agree

2016-10-24 15:16 UTC, alekseyC64 commented on notes_app/client/app/login/login.component.js
> +        $state.go('main.note.list');
@evgeny-sav if you won't perform any action on this you have to answer on the comment at least

2016-10-25 10:25 UTC, ghost approved these changes

2016-10-26 13:01 UTC, alekseyC64 commented
:+1:

2016-10-26 13:07 UTC, merged